/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

/**
 *
 * @author LAPTOP
 */
public class calApp_gui extends javax.swing.JFrame {

    /**
     * Creates new form calApp_gui
     */
    public calApp_gui() {
        initComponents();
         bon.setEnabled(false);
    }
    public void enable(){
        bon.setEnabled(false);
        boff.setEnabled(true);
        text.setEnabled(true);
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        b0.setEnabled(true);
        ppowr2.setEnabled(true);
        ppowr3.setEnabled(true);
        b_eql.setEnabled(true);
        b_clear.setEnabled(true);
        b_minus.setEnabled(true);
        b_div.setEnabled(true);
        b_dot.setEnabled(true);
        b_fact.setEnabled(true);
        b_plus.setEnabled(true);
        b_mult.setEnabled(true);
        b_delete.setEnabled(true);
        b_abs.setEnabled(true);
         b_mod.setEnabled(true);
          b_ln.setEnabled(true);
           b_sin.setEnabled(true);
           b_cos.setEnabled(true);
          b_tan.setEnabled(true);
          b_sinh.setEnabled(true);
           b_cosh.setEnabled(true);
          b_tanh.setEnabled(true);
          b_exp.setEnabled(true);
           b_xpy.setEnabled(true);
          b_pers.setEnabled(true);
          b_sqrt.setEnabled(true);
           b_oppo.setEnabled(true);
           b_log.setEnabled(true);
            b_pi.setEnabled(true);
           b_mi.setEnabled(true);
          
    } 
      public void disable(){
        text.setEnabled(false);
        bon.setEnabled(true);
        boff.setEnabled(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
        b5.setEnabled(false);
        b6.setEnabled(false);
        b7.setEnabled(false);
        b8.setEnabled(false);
        b9.setEnabled(false);
        b0.setEnabled(false);
        b_dot.setEnabled(false);
        ppowr2.setEnabled(false);
        ppowr3.setEnabled(false);
        b_eql.setEnabled(false);
        b_clear.setEnabled(false);
        b_minus.setEnabled(false);
        b_div.setEnabled(false);
        b_dot.setEnabled(false);
        b_fact.setEnabled(false);
        b_plus.setEnabled(false);
        b_mult.setEnabled(false);
        b_delete.setEnabled(false);
         b_abs.setEnabled(false);
         b_mod.setEnabled(false);
          b_ln.setEnabled(false);
           b_sin.setEnabled(false);
           b_cos.setEnabled(false);
          b_tan.setEnabled(false);
          b_sinh.setEnabled(false);
           b_cosh.setEnabled(false);
          b_tanh.setEnabled(false);
          b_exp.setEnabled(false);
           b_xpy.setEnabled(false);
          b_pers.setEnabled(false);
          b_sqrt.setEnabled(false);
           b_oppo.setEnabled(false);
           b_log.setEnabled(false);
            b_pi.setEnabled(false);
           b_mi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        text = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b_eql = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b_dot = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b_mult = new javax.swing.JButton();
        b_div = new javax.swing.JButton();
        b_minus = new javax.swing.JButton();
        b_plus = new javax.swing.JButton();
        ppowr2 = new javax.swing.JButton();
        ppowr3 = new javax.swing.JButton();
        b_fact = new javax.swing.JButton();
        b_clear = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        bon = new javax.swing.JRadioButton();
        boff = new javax.swing.JRadioButton();
        b_sqrt = new javax.swing.JButton();
        b_cosh = new javax.swing.JButton();
        b_pers = new javax.swing.JButton();
        b_oppo = new javax.swing.JButton();
        b_sinh = new javax.swing.JButton();
        b_tanh = new javax.swing.JButton();
        b_sin = new javax.swing.JButton();
        b_tan = new javax.swing.JButton();
        b_cos = new javax.swing.JButton();
        b_exp = new javax.swing.JButton();
        b_ln = new javax.swing.JButton();
        b_xpy = new javax.swing.JButton();
        b_abs = new javax.swing.JButton();
        b_mod = new javax.swing.JButton();
        b_log = new javax.swing.JButton();
        b_mi = new javax.swing.JButton();
        b_pi = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculator");
        setResizable(false);

        text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(255, 255, 255));
        b9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b_eql.setBackground(new java.awt.Color(51, 0, 51));
        b_eql.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_eql.setText("=");
        b_eql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eqlActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(255, 255, 255));
        b7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(255, 255, 255));
        b8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b_dot.setBackground(new java.awt.Color(255, 255, 255));
        b_dot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_dot.setText(".");
        b_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dotActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(255, 255, 255));
        b0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b_mult.setBackground(new java.awt.Color(255, 255, 255));
        b_mult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_mult.setText("*");
        b_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_multActionPerformed(evt);
            }
        });

        b_div.setBackground(new java.awt.Color(255, 255, 255));
        b_div.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_div.setText("/");
        b_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_divActionPerformed(evt);
            }
        });

        b_minus.setBackground(new java.awt.Color(255, 255, 255));
        b_minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_minus.setText("-");
        b_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_minusActionPerformed(evt);
            }
        });

        b_plus.setBackground(new java.awt.Color(255, 255, 255));
        b_plus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_plus.setText("+");
        b_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_plusActionPerformed(evt);
            }
        });

        ppowr2.setBackground(new java.awt.Color(255, 255, 255));
        ppowr2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ppowr2.setText("x^2");
        ppowr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppowr2ActionPerformed(evt);
            }
        });

        ppowr3.setBackground(new java.awt.Color(255, 255, 255));
        ppowr3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ppowr3.setText("x^3");
        ppowr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppowr3ActionPerformed(evt);
            }
        });

        b_fact.setBackground(new java.awt.Color(255, 255, 255));
        b_fact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_fact.setText("x!");
        b_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_factActionPerformed(evt);
            }
        });

        b_clear.setBackground(new java.awt.Color(0, 0, 0));
        b_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_clear.setForeground(new java.awt.Color(255, 255, 255));
        b_clear.setText("clear");
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });

        b_delete.setBackground(new java.awt.Color(255, 255, 255));
        b_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_delete.setText("delete");
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });

        buttonGroup1.add(bon);
        bon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bon.setText("ON");
        bon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonActionPerformed(evt);
            }
        });

        buttonGroup1.add(boff);
        boff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boff.setText("OFF");
        boff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boffActionPerformed(evt);
            }
        });

        b_sqrt.setBackground(new java.awt.Color(51, 0, 51));
        b_sqrt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_sqrt.setForeground(new java.awt.Color(255, 255, 255));
        b_sqrt.setText("sqrt");
        b_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sqrtActionPerformed(evt);
            }
        });

        b_cosh.setBackground(new java.awt.Color(51, 0, 51));
        b_cosh.setForeground(new java.awt.Color(255, 255, 255));
        b_cosh.setText("cosh");
        b_cosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_coshActionPerformed(evt);
            }
        });

        b_pers.setBackground(new java.awt.Color(255, 255, 255));
        b_pers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_pers.setText("%");
        b_pers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_persActionPerformed(evt);
            }
        });

        b_oppo.setBackground(new java.awt.Color(255, 255, 255));
        b_oppo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_oppo.setText("1/x");
        b_oppo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_oppoActionPerformed(evt);
            }
        });

        b_sinh.setBackground(new java.awt.Color(51, 0, 51));
        b_sinh.setForeground(new java.awt.Color(255, 255, 255));
        b_sinh.setText("sinh");
        b_sinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sinhActionPerformed(evt);
            }
        });

        b_tanh.setBackground(new java.awt.Color(51, 0, 51));
        b_tanh.setForeground(new java.awt.Color(255, 255, 255));
        b_tanh.setText("tanh");
        b_tanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tanhActionPerformed(evt);
            }
        });

        b_sin.setBackground(new java.awt.Color(51, 0, 51));
        b_sin.setForeground(new java.awt.Color(255, 255, 255));
        b_sin.setText("sin");
        b_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sinActionPerformed(evt);
            }
        });

        b_tan.setBackground(new java.awt.Color(51, 0, 51));
        b_tan.setForeground(new java.awt.Color(255, 255, 255));
        b_tan.setText("tan");
        b_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tanActionPerformed(evt);
            }
        });

        b_cos.setBackground(new java.awt.Color(51, 0, 51));
        b_cos.setForeground(new java.awt.Color(255, 255, 255));
        b_cos.setText("cos");
        b_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cosActionPerformed(evt);
            }
        });

        b_exp.setBackground(new java.awt.Color(51, 0, 51));
        b_exp.setForeground(new java.awt.Color(255, 255, 255));
        b_exp.setText("exp");
        b_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_expActionPerformed(evt);
            }
        });

        b_ln.setBackground(new java.awt.Color(51, 0, 51));
        b_ln.setForeground(new java.awt.Color(255, 255, 255));
        b_ln.setText("ln");
        b_ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lnActionPerformed(evt);
            }
        });

        b_xpy.setBackground(new java.awt.Color(51, 0, 51));
        b_xpy.setForeground(new java.awt.Color(255, 255, 255));
        b_xpy.setText("x^y");
        b_xpy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xpyActionPerformed(evt);
            }
        });

        b_abs.setBackground(new java.awt.Color(51, 0, 51));
        b_abs.setForeground(new java.awt.Color(255, 255, 255));
        b_abs.setText("abs");
        b_abs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_absActionPerformed(evt);
            }
        });

        b_mod.setBackground(new java.awt.Color(51, 0, 51));
        b_mod.setForeground(new java.awt.Color(255, 255, 255));
        b_mod.setText("modolus");
        b_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modActionPerformed(evt);
            }
        });

        b_log.setBackground(new java.awt.Color(51, 0, 51));
        b_log.setForeground(new java.awt.Color(255, 255, 255));
        b_log.setText("log");
        b_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logActionPerformed(evt);
            }
        });

        b_mi.setBackground(new java.awt.Color(51, 0, 51));
        b_mi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_mi.setForeground(new java.awt.Color(255, 255, 255));
        b_mi.setText("-");
        b_mi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_miActionPerformed(evt);
            }
        });

        b_pi.setBackground(new java.awt.Color(51, 0, 51));
        b_pi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b_pi.setForeground(new java.awt.Color(255, 255, 255));
        b_pi.setText("PI");
        b_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_piActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bon)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b_log, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b_sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b_ln, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b_abs, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b_cosh)
                                            .addComponent(b_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(b_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b_xpy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_tanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b_sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(b_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(b9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b_mi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_tan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(boff)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(b_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ppowr2))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(b_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(b3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(b_eql, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ppowr3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(b_mult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_minus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_div, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(b_pers, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b_oppo))
                        .addComponent(b_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b_mi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b_log, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_abs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_ln)
                            .addComponent(b_exp)
                            .addComponent(b_xpy)
                            .addComponent(b_sqrt)
                            .addComponent(b_tan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_sinh)
                            .addComponent(b_cosh)
                            .addComponent(b_tanh)
                            .addComponent(b_sin)
                            .addComponent(b_cos))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ppowr2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ppowr3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_fact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_eql)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b_oppo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_pers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_div, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        text.setText(text.getText()+"1");
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"2");
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"3");
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"4");
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"5");
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
 text.setText(text.getText()+"6");        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"7");
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"8");
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"9");
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"0");
    }//GEN-LAST:event_b0ActionPerformed

    private void b_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dotActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+".");
    }//GEN-LAST:event_b_dotActionPerformed

    private void b_eqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eqlActionPerformed
        // TODO add your handling code here:
        switch(operation){
            case'+':
                n2=Double.parseDouble(text.getText());
                result=n1+n2;
                break;
                case'-':
                n2=Double.parseDouble(text.getText());
                result=n1-n2;
                break;
                case'*':
                n2=Double.parseDouble(text.getText());
                result=n1*n2;
                break;
                case'/':
                n2=Double.parseDouble(text.getText());
                result=n1/n2;
                break;
                case'!':
                result=fact(n1);
                break;
                case'^':
                result=n1*n1;
                break;
                case'3':
                result=n1*n1*n1;
                break;
                case's':
                n1=Math.toRadians(n1);
                result=(Math.sin(n1));
                text.setText(Double.toString(result));
                break;
                case'q':
                result=(Math.sqrt(n1));
                text.setText(Double.toString(result));
                break;
                case'c':
                n1=Math.toRadians(n1);
                result=(Math.cos(n1));
                text.setText(Double.toString(result));
                break;
                case't':
                n1=Math.toRadians(n1);
                result=(Math.tan(n1));
                text.setText(Double.toString(result));
                break;
                case'l':
                result=(Math.log(n1));
                text.setText(Double.toString(result));
                break;
                case'e':
                result=(Math.exp(n1));
                text.setText(Double.toString(result));
                break; 
                case'p':
                n2=Double.parseDouble(text.getText());
                result=(Math.pow(n1,n2));
                text.setText(Double.toString(result));
                break;
                case'7':
                n1=Math.toRadians(n1);
                result=(Math.sinh(n1));
                text.setText(Double.toString(result));
                break;
                case'8':
                n1=Math.toRadians(n1);
                result=(Math.cosh(n1));
                text.setText(Double.toString(result));
                break;
                case'9':
                n1=Math.toRadians(n1);
                result=(Math.tanh(n1));
                text.setText(Double.toString(result));
                break;
                case'|':
                result=(Math.abs(n1));
                text.setText(Double.toString(result));
                break;
                case'%':
                result=n1/100;
                text.setText(Double.toString(result));
                break;
                case'm':
                n2=Double.parseDouble(text.getText());    
                result=n1%n2;
                text.setText(Double.toString(result));
                break;
                case'o':
                result=1/n1;
                text.setText(Double.toString(result));
                break;
                case'g':
                result=(Math.log10(n1));
                text.setText(Double.toString(result));
                break;
               
        }
        text.setText(String.format("%.1f",result));
         
    }//GEN-LAST:event_b_eqlActionPerformed
double fact(double x){
    if(x==1)
        return 1;
    else
        return x*fact(x-1);
}
    private void b_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_plusActionPerformed
        // TODO add your handling code here:
        n1=Double.parseDouble(text.getText());
        operation='+';
        text.setText("");
         label.setText("+"+n1);
    }//GEN-LAST:event_b_plusActionPerformed

    private void b_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_minusActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='-';
        text.setText("");
         label.setText("-"+n1);
    }//GEN-LAST:event_b_minusActionPerformed

    private void b_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_multActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='*';
        text.setText("");
         label.setText("*"+n1);
    }//GEN-LAST:event_b_multActionPerformed

    private void b_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_divActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='/';
        text.setText("");
        label.setText("/"+n1);
    }//GEN-LAST:event_b_divActionPerformed

    private void b_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_factActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='!';
        text.setText("");
         label.setText("!"+n1);
    }//GEN-LAST:event_b_factActionPerformed

    private void ppowr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppowr2ActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='^';
        text.setText("");
         label.setText("^"+(n1));
    }//GEN-LAST:event_ppowr2ActionPerformed

    private void ppowr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppowr3ActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='3';
        text.setText("");
         label.setText("^"+n1);
    }//GEN-LAST:event_ppowr3ActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        // TODO add your handling code here:
        text.setText("");
    }//GEN-LAST:event_b_clearActionPerformed

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
        // TODO add your handling code here:
        int length=text.getText().length();
        int number=text.getText().length()-1;
        String store;
        if(length>0){
            StringBuilder back= new StringBuilder(text.getText());
            back.deleteCharAt(number);
            store=back.toString();
            text.setText(store);
            
        }
    }//GEN-LAST:event_b_deleteActionPerformed

    private void bonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonActionPerformed
        // TODO add your handling code here:
        enable();
    }//GEN-LAST:event_bonActionPerformed

    private void boffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boffActionPerformed
        // TODO add your handling code here:
        disable();
    }//GEN-LAST:event_boffActionPerformed

    private void b_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sqrtActionPerformed
        // TODO add your handling code here:
        n1=Double.parseDouble(text.getText());
        operation='q';
        text.setText("");
         label.setText("sqrt "+n1);
    }//GEN-LAST:event_b_sqrtActionPerformed

    private void b_coshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_coshActionPerformed
        // TODO add your handling code here:
        n1=Double.parseDouble(text.getText());
        operation='8';
        text.setText("");
         label.setText("cosh "+n1);
        
    }//GEN-LAST:event_b_coshActionPerformed

    private void b_sinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sinhActionPerformed
        // TODO add your handling code here:
        n1=Double.parseDouble(text.getText());
        operation='7';
        text.setText("");
         label.setText("sinh  "+n1);
    }//GEN-LAST:event_b_sinhActionPerformed

    private void b_tanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tanhActionPerformed
        // TODO add your handling code here:
        n1=Double.parseDouble(text.getText());
        operation='9';
        text.setText("");
         label.setText("tanh "+n1);
    }//GEN-LAST:event_b_tanhActionPerformed

    private void b_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sinActionPerformed
        // TODO add your handling code here:
       n1=Double.parseDouble(text.getText());
        operation='s';
        text.setText("");
         label.setText("sin "+n1);
    }//GEN-LAST:event_b_sinActionPerformed

    private void b_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tanActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='t';
        text.setText("");
         label.setText("tan "+n1);
    }//GEN-LAST:event_b_tanActionPerformed

    private void b_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cosActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='c';
        text.setText("");
         label.setText("cos "+n1);
    }//GEN-LAST:event_b_cosActionPerformed

    private void b_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_expActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='e';
        text.setText("");
         label.setText("e^"+n1);
    }//GEN-LAST:event_b_expActionPerformed

    private void b_lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lnActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='l';
        text.setText("");
         label.setText("ln"+n1);
        
    }//GEN-LAST:event_b_lnActionPerformed

    private void b_xpyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xpyActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='p';
        text.setText("");
         label.setText("^"+n1);
    }//GEN-LAST:event_b_xpyActionPerformed

    private void b_absActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_absActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='|';
        text.setText("");
         label.setText("|"+n1+"|");
    }//GEN-LAST:event_b_absActionPerformed

    private void b_persActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_persActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='%';
        text.setText("");
         label.setText("%"+n1);
    }//GEN-LAST:event_b_persActionPerformed

    private void b_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='m';
        text.setText("");
         label.setText(n1+"%");
    }//GEN-LAST:event_b_modActionPerformed

    private void b_oppoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_oppoActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='o';
        text.setText("");
         label.setText("1/"+n1);
    }//GEN-LAST:event_b_oppoActionPerformed

    private void b_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logActionPerformed
        // TODO add your handling code here:
         n1=Double.parseDouble(text.getText());
        operation='g';
        text.setText("");
         label.setText("log"+n1);
        
    }//GEN-LAST:event_b_logActionPerformed

    private void b_miActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_miActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"-");
    }//GEN-LAST:event_b_miActionPerformed

    private void b_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_piActionPerformed
        // TODO add your handling code here:
         text.setText(text.getText()+"3.14");
    }//GEN-LAST:event_b_piActionPerformed
double n1,n2,result;
char operation;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {char operation;

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calApp_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calApp_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calApp_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calApp_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calApp_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton b_abs;
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_cos;
    private javax.swing.JButton b_cosh;
    private javax.swing.JButton b_delete;
    private javax.swing.JButton b_div;
    private javax.swing.JButton b_dot;
    private javax.swing.JButton b_eql;
    private javax.swing.JButton b_exp;
    private javax.swing.JButton b_fact;
    private javax.swing.JButton b_ln;
    private javax.swing.JButton b_log;
    private javax.swing.JButton b_mi;
    private javax.swing.JButton b_minus;
    private javax.swing.JButton b_mod;
    private javax.swing.JButton b_mult;
    private javax.swing.JButton b_oppo;
    private javax.swing.JButton b_pers;
    private javax.swing.JButton b_pi;
    private javax.swing.JButton b_plus;
    private javax.swing.JButton b_sin;
    private javax.swing.JButton b_sinh;
    private javax.swing.JButton b_sqrt;
    private javax.swing.JButton b_tan;
    private javax.swing.JButton b_tanh;
    private javax.swing.JButton b_xpy;
    private javax.swing.JRadioButton boff;
    private javax.swing.JRadioButton bon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel label;
    private javax.swing.JButton ppowr2;
    private javax.swing.JButton ppowr3;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
